In [3]:
import numpy as np
from numpy.linalg import matrix_power
#Matriz A simtetrica
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
k = int(input("Dime el exponente: "))

#numpy, linalg.matrix_power(a, n) a es la matriz y k el exponente, 
#source:https://numpy.org/doc/2.1/reference/generated/numpy.linalg.matrix_power.html
result = np.linalg.matrix_power(A, k)
  #Imprimir resultados
print("A:")
print(A)
print(f"A elevado a {k}")
print(result)

Dime el exponente:  8


A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
A elevado a 8
[[ 510008400  626654232  743300064]
 [1154967822 1419124617 1683281412]
 [1799927244 2211595002 2623262760]]
